spotify.client.id=edd41b4e3bf94ba380ab27bedecc4da4
spotify.client.secret=529a1917e8304329815f685b2c1125e6
spotify.redirect.uri=http://localhost:8080/callback

spring.security.oauth2.client.registration.spotify.client-id=edd41b4e3bf94ba380ab27bedecc4da4
spring.security.oauth2.client.registration.spotify.client-secret=529a1917e8304329815f685b2c1125e6
spring.security.oauth2.client.registration.spotify.redirect-uri=http://localhost:8080/login/oauth2/code/spotify

spring.security.oauth2.client.registration.spotify.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.spotify.scope=user-library-read

spring.security.oauth2.client.provider.spotify.authorization-uri=https://accounts.spotify.com/authorize
spring.security.oauth2.client.provider.spotify.token-uri=https://accounts.spotify.com/api/token
spring.security.oauth2.client.provider.spotify.user-info-uri=https://api.spotify.com/v1/me
spring.security.oauth2.client.provider.spotify.user-name-attribute=id



